// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmyVIxWL3VPKkVObrbz19fJQmw1YfNYmo',
    appId: '1:485146306968:web:c1281f163a4a9fa32ce3ed',
    messagingSenderId: '485146306968',
    projectId: 'water-3669a',
    authDomain: 'water-3669a.firebaseapp.com',
    storageBucket: 'water-3669a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQOzEpJvchDRjkaX28ZCRzqxGwm4Zj0k',
    appId: '1:485146306968:android:a824c6d68663847c2ce3ed',
    messagingSenderId: '485146306968',
    projectId: 'water-3669a',
    storageBucket: 'water-3669a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuH615E8ZddCK4FYMS3X6hEizgEhHEUaQ',
    appId: '1:485146306968:ios:66bf7f2df8544b102ce3ed',
    messagingSenderId: '485146306968',
    projectId: 'water-3669a',
    storageBucket: 'water-3669a.firebasestorage.app',
    iosBundleId: 'com.example.water',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuH615E8ZddCK4FYMS3X6hEizgEhHEUaQ',
    appId: '1:485146306968:ios:66bf7f2df8544b102ce3ed',
    messagingSenderId: '485146306968',
    projectId: 'water-3669a',
    storageBucket: 'water-3669a.firebasestorage.app',
    iosBundleId: 'com.example.water',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmyVIxWL3VPKkVObrbz19fJQmw1YfNYmo',
    appId: '1:485146306968:web:f2ee75ee9e3b45c22ce3ed',
    messagingSenderId: '485146306968',
    projectId: 'water-3669a',
    authDomain: 'water-3669a.firebaseapp.com',
    storageBucket: 'water-3669a.firebasestorage.app',
  );
}
